import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Building Patient Trust in AI-Powered Healthcare Services | Get MedReception',
  description: 'Learn how healthcare providers can build and maintain patient trust when implementing AI-powered services. Evidence-based strategies for transparent, ethical AI adoption in medical practice.',
  keywords: 'AI healthcare, patient trust, artificial intelligence medicine, healthcare technology, patient education, medical AI ethics',
  openGraph: {
    title: 'Building Patient Trust in AI-Powered Healthcare Services',
    description: 'Evidence-based strategies for building patient confidence in AI-powered healthcare.',
    type: 'article',
    publishedTime: '2024-01-15T10:00:00Z',
  },
}

export default function BlogPost() {
  return (
    <main className="min-h-screen bg-white">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-[var(--color-dark)] to-[var(--color-primary)] py-20 text-white">
        <div className="max-w-4xl mx-auto px-6">
          {/* Breadcrumb */}
          <nav className="text-sm mb-8 text-white/80 text-center">
            <a href="/" className="hover:text-white transition-colors">Home</a>
            <span className="mx-2">›</span>
            <a href="/blog" className="hover:text-white transition-colors">Resources</a>
            <span className="mx-2">›</span>
            <span className="text-white">Article</span>
          </nav>

          {/* Category */}
          <div className="text-xs uppercase tracking-widest text-white/70 mb-4 text-center">
            Patient Education
          </div>

          {/* Title */}
          <h1 className="font-cormorant text-5xl font-light leading-tight max-w-3xl mx-auto text-center mb-8">
            Building Patient Trust in AI-Powered Healthcare Services
          </h1>

          {/* Meta */}
          <div className="flex items-center justify-center gap-6 text-sm text-white/80">
            <span>Published January 15, 2024</span>
            <span>•</span>
            <span>7 min read</span>
            <span>•</span>
            <span>By Dr. MedReception Team</span>
          </div>
        </div>
      </section>

      {/* Article Body */}
      <article className="bg-white py-20">
        <div className="max-w-3xl mx-auto px-6">
          {/* Opening Hook */}
          <p className="text-[var(--color-ink)] leading-loose text-lg mb-8">
            When you call your doctor's office and hear an AI-powered voice assistant, or receive a text reminder generated by an algorithm, a natural question arises: "Can I trust this?" You're not alone in wondering. As artificial intelligence becomes increasingly integrated into healthcare delivery, patients worldwide are navigating this new landscape with a mix of curiosity, skepticism, and concern. The good news? Building trust in AI-powered healthcare isn't just possible—it's already happening in practices that prioritize transparency, ethics, and patient-centered care.
          </p>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-8">
            Understanding how AI works in your healthcare experience, and what safeguards are in place, can transform apprehension into confidence. Let's explore how modern medical practices are building that bridge of trust.
          </p>

          {/* Section 1 */}
          <h2 className="font-cormorant text-3xl text-[var(--color-ink)] mt-12 mb-4">
            Understanding AI in Healthcare: What It Is and What It Isn't
          </h2>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-6">
            First, it's important to demystify what AI actually does in a medical setting. AI in healthcare typically refers to machine learning systems that can process large amounts of data, recognize patterns, and perform specific tasks—but they're not replacing your doctor's judgment or care.
          </p>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-6">
            In most practices today, AI handles administrative functions: scheduling appointments, sending reminders, answering common questions about office hours or insurance, and routing calls to the appropriate department. Think of it as a highly efficient administrative assistant that never takes a lunch break and can help multiple patients simultaneously.
          </p>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-8">
            What AI doesn't do: diagnose your condition, prescribe medication, or make clinical decisions. Those responsibilities remain firmly in the hands of licensed healthcare professionals who have spent years training to care for patients like you.
          </p>

          {/* Section 2 */}
          <h2 className="font-cormorant text-3xl text-[var(--color-ink)] mt-12 mb-4">
            The Transparency Principle: How Your Data Is Protected
          </h2>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-6">
            One of the biggest concerns patients have about AI in healthcare centers on privacy and data security. This concern is not only valid—it's essential. Your medical information is among your most sensitive personal data, and you have every right to know how it's being handled.
          </p>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-6">
            Reputable healthcare AI systems operate under strict HIPAA compliance, the same federal privacy standards that govern all medical records. This means your conversations, appointment details, and health information are encrypted, stored securely, and never sold to third parties or used for marketing purposes.
          </p>

          <div className="bg-[var(--color-light)] border-l-4 border-[var(--color-primary)] p-6 my-8">
            <p className="text-[var(--color-ink)] italic text-xl font-cormorant">
              "Trust in healthcare AI isn't built through technology alone—it's built through transparency, accountability, and putting patients first at every step."
            </p>
          </div>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-8">
            When evaluating a healthcare provider that uses AI, don't hesitate to ask direct questions: How is my data stored? Who has access to it? What happens if I prefer to speak with a human? Practices that prioritize trust will have clear, straightforward answers.
          </p>

          {/* Section 3 */}
          <h2 className="font-cormorant text-3xl text-[var(--color-ink)] mt-12 mb-4">
            The Human-AI Partnership: Enhanced Care, Not Replacement
          </h2>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-6">
            The most successful implementations of AI in healthcare follow a partnership model. AI handles routine, time-consuming administrative tasks, freeing healthcare professionals to focus on what they do best: providing compassionate, personalized medical care.
          </p>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-6">
            Consider this scenario: Instead of your doctor's staff spending hours each day manually calling to confirm appointments, an AI system sends automated reminders and processes confirmations. This means when you arrive for your appointment, your provider isn't rushed or distracted by administrative backlog—they can give you their full attention.
          </p>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-8">
            Research published in the Journal of Medical Internet Research found that when AI handles routine administrative tasks, patient wait times decrease by an average of 20-30%, and providers report higher job satisfaction and lower burnout. When doctors are less stressed and have more time, patient care quality improves across the board.
          </p>

          {/* Section 4 */}
          <h2 className="font-cormorant text-3xl text-[var(--color-ink)] mt-12 mb-4">
            Red Flags vs. Green Flags: Evaluating AI Implementation
          </h2>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-6">
            Not all AI implementations are created equal. As a patient, you can evaluate whether a healthcare practice is using AI responsibly by looking for these indicators:
          </p>

          <div className="space-y-4 my-8">
            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 mt-1">
                <svg className="w-6 h-6 text-[var(--color-accent)]" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <p className="text-[var(--color-ink)] leading-loose text-base">
                <strong>Green Flag:</strong> The practice clearly discloses when you're interacting with AI and offers easy access to human staff when needed.
              </p>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 mt-1">
                <svg className="w-6 h-6 text-[var(--color-accent)]" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <p className="text-[var(--color-ink)] leading-loose text-base">
                <strong>Green Flag:</strong> Privacy policies are written in plain language and explain exactly how AI uses your information.
              </p>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 mt-1">
                <svg className="w-6 h-6 text-[var(--color-accent)]" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <p className="text-[var(--color-ink)] leading-loose text-base">
                <strong>Green Flag:</strong> Staff can explain the benefits of AI tools and address concerns without dismissing them.
              </p>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 mt-1">
                <svg className="w-6 h-6 text-[var(--color-accent)]" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <p className="text-[var(--color-ink)] leading-loose text-base">
                <strong>Green Flag:</strong> You can opt out of AI-powered interactions without penalty or reduced service quality.
              </p>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 mt-1">
                <svg className="w-6 h-6 text-[var(--color-accent)]" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <p className="text-[var(--color-ink)] leading-loose text-base">
                <strong>Green Flag:</strong> The AI system recognizes its limitations and seamlessly transfers complex issues to human staff.
              </p>
            </div>
          </div>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-8">
            Conversely, be cautious if a practice is secretive about AI use, makes it difficult to reach human staff, or can't clearly explain their data protection measures. Your comfort and trust should be priorities.
          </p>

          {/* Section 5 */}
          <h2 className="font-cormorant text-3xl text-[var(--color-ink)] mt-12 mb-4">
            The Benefits You Might Not See (But Definitely Feel)
          </h2>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-6">
            When AI is implemented thoughtfully in healthcare, the benefits extend far beyond convenience. Patients in practices using AI administrative tools report several improvements that directly enhance their care experience:
          </p>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-4">
            <strong>Reduced wait times:</strong> When scheduling and routine inquiries are handled efficiently by AI, phone lines are clearer for urgent matters, and in-office wait times decrease.
          </p>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-4">
            <strong>Better appointment adherence:</strong> Automated reminders sent via text or email help patients remember appointments, reducing missed visits and improving continuity of care.
          </p>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-4">
            <strong>24/7 access to basic information:</strong> Need to know office hours at 10 PM? Want to confirm what insurance is accepted before your appointment tomorrow? AI-powered systems can answer these questions anytime.
          </p>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-8">
            <strong>More focused provider attention:</strong> When administrative burden decreases, your doctor or nurse practitioner can spend more time listening to your concerns, explaining treatment options, and providing the personalized care you deserve.
          </p>

          {/* Section 6 */}
          <h2 className="font-cormorant text-3xl text-[var(--color-ink)] mt-12 mb-4">
            Questions to Ask Your Healthcare Provider
          </h2>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-6">
            Empowering yourself with information is key to building trust. Here are important questions to ask your healthcare provider about their use of AI:
          </p>

          <div className="space-y-4 my-8">
            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 mt-1">
                <svg className="w-6 h-6 text-[var(--color-primary)]" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                </svg>
              </div>
              <p className="text-[var(--color-ink)] leading-loose text-base">
                "What specific tasks does AI handle in your practice, and what always requires a human?"
              </p>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 mt-1">
                <svg className="w-6 h-6 text-[var(--color-primary)]" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                </svg>
              </div>
              <p className="text-[var(--color-ink)] leading-loose text-base">
                "How is my health information protected when AI systems access it?"
              </p>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 mt-1">
                <svg className="w-6 h-6 text-[var(--color-primary)]" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                </svg>
              </div>
              <p className="text-[var(--color-ink)] leading-loose text-base">
                "If I'm uncomfortable with AI interactions, what are my alternatives?"
              </p>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 mt-1">
                <svg className="w-6 h-6 text-[var(--color-primary)]" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                </svg>
              </div>
              <p className="text-[var(--color-ink)] leading-loose text-base">
                "How do you ensure the AI system respects patient privacy and confidentiality?"
              </p>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 mt-1">
                <svg className="w-6 h-6 text-[var(--color-primary)]" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                </svg>
              </div>
              <p className="text-[var(--color-ink)] leading-loose text-base">
                "What training have staff received to work alongside these AI tools?"
              </p>
            </div>
          </div>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-8">
            A trustworthy practice will welcome these questions and provide clear, honest answers. If staff seem defensive or evasive, that's valuable information too.
          </p>

          {/* Closing */}
          <h2 className="font-cormorant text-3xl text-[var(--color-ink)] mt-12 mb-4">
            Moving Forward with Confidence
          </h2>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-6">
            The integration of AI into healthcare is not a trend—it's an evolution in how medical practices can serve patients more efficiently while maintaining the human connection that makes healthcare meaningful. Like any tool, AI's value depends entirely on how it's implemented and the priorities of those using it.
          </p>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-6">
            Trust is built through transparency, proven reliability, and consistent patient-centered care. When healthcare providers embrace AI as a way to enhance—not replace—human connection, everyone benefits. You receive more responsive service, shorter wait times, and access to providers who have more bandwidth to truly listen and care.
          </p>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-8">
            As you navigate healthcare options, remember that you have the right to understand, question, and choose providers whose approach to technology aligns with your values. The best healthcare practices will earn your trust not by asking for it blindly, but by demonstrating every day that your care, privacy, and wellbeing come first—whether you're interacting with a person or an AI-powered system designed to serve you.
          </p>

          <p className="text-[var(--color-ink)] leading-loose text-base mb-8">
            If you have concerns about AI in your current healthcare experience, don't stay silent. Speak up, ask questions, and seek providers who take those questions seriously. Your trust is valuable—it should be earned, not assumed.
          </p>
        </div>

        {/* Author Box */}
        <div className="bg-[var(--color-cream)] rounded-2xl p-8 max-w-3xl mx-auto my-12 flex gap-6 items-start">
          <div className="flex-shrink-0">
            <div className="bg-[var(--color-light)] rounded-full w-16 h-16 flex items-center justify-center">
              <svg className="w-8 h-8 text-[var(--color-primary)]" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
              </svg>
            </div>
          </div>
          <div>
            <h3 className="font-cormorant text-xl font-semibold text-[var(--color-ink)] mb-2">
              Written by the Get MedReception Clinical Team
            </h3>
            <p className="text-[var(--color-muted)] text-sm leading-relaxed">
              Board-certified providers specializing in Other Medical, dedicated to delivering evidence-based patient education and compassionate care guidance.
            </p>
          </div>
        </div>
      </article>

      {/* Related Articles */}
      <section className="bg-[var(--color-cream)] py-16">
        <div className="max-w-7xl mx-auto px-6">
          <h3 className="font-cormorant text-3xl text-[var(--color-ink)] mb-8 text-center">
            Related Resources
          </h3>

          <div className="grid md:grid-cols-3 gap-8">
            {/* Card 1 */}
            <a href="/blog" className="group bg-white rounded-xl overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300">
              <div className="bg-gradient-to-br from-[var(--color-dark)] to-[var(--color-primary)] h-48 flex items-center justify-center">
                <svg className="w-16 h-16 text-white/80" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" />
                </svg>
              </div>
              <div className="p-6">
                <div className="text-xs uppercase tracking-wider text-[var(--color-accent)] mb-2">
                  Privacy & Security
                </div>
                <h4 className="font-cormorant text-xl font-semibold text-[var(--color-ink)] mb-2 group-hover:text-[var(--color-primary)] transition-colors">
                  Understanding HIPAA Compliance in Digital Healthcare
                </h4>
                <p className="text-[var(--color-muted)] text-sm leading-relaxed">
                  Learn how your medical information is protected in the digital age and what rights you have as a patient.
                </p>
              </div>
            </a>

            {/* Card 2 */}
            <a href="/blog" className="group bg-white rounded-xl overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300">
              <div className="bg-gradient-to-br from-[var(--color-dark)] to-[var(--color-primary)] h-48 flex items-center justify-center">
                <svg className="w-16 h-16 text-white/80" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155" />
                </svg>
              </div>
              <div className="p-6">
                <div className="text-xs uppercase tracking-wider text-[var(--color-accent)] mb-2">
                  Patient Communication
                </div>
                <h4 className="font-cormorant text-xl font-semibold text-[var(--color-ink)] mb-2 group-hover:text-[var(--color-primary)] transition-colors">
                  How to Communicate Effectively With Your Healthcare Team
                </h4>
                <p className="text-[var(--color-muted)] text-sm leading-relaxed">
                  Tips for making the most of your appointments and ensuring your concerns are heard and addressed.
                </p>
              </div>
            </a>

            {/* Card 3 */}
            <a href="/blog" className="group bg-white rounded-xl overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300">
              <div className="bg-gradient-to-br from-[var(--color-dark)] to-[var(--color-primary)] h-48 flex items-center justify-center">
                <svg className="w-16 h-16 text-white/80" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5" />
                </svg>
              </div>
              <div className="p-6">
                <div className="text-xs uppercase tracking-wider text-[var(--color-accent)] mb-2">
                  Access to Care
                </div>
                <h4 className="font-cormorant text-xl font-semibold text-[var(--color-ink)] mb-2 group-hover:text-[var(--color-primary)] transition-colors">
                  The Future of Healthcare Scheduling and Access
                </h4>
                <p className="text-[var(--color-muted)] text-sm leading-relaxed">
                  Discover how technology is making it easier to access the care you need, when you need it.
                </p>
              </div>
            </a>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-gradient-to-br from-[var(--color-dark)] to-[var(--color-primary)] py-20 text-white text-center">
        <div className="max-w-4xl mx-auto px-6">
          <h2 className="font-cormorant text-4xl font-light mb-4">
            Ready to Take the Next Step?
          </h2>
          <p className="text-xl mb-8 text-white/90">
            Our team is here to help.
          </p>
          <a
            href="/contact"
            className="inline-block bg-[var(--color-accent)] hover:bg-[var(--color-accent-dark)] text-white font-medium px-8 py-4 rounded-lg transition-all duration-300 hover:scale-105 hover:shadow-xl"
          >
            Contact Us Today
          </a>
        </div>
      </section>
    </main>
  )
}